import { Name } from '../state/names/name.model';

export class InMemoryDataService {
  createDb() {
    const names: Array<Name> = [
      { id: 1, name: 'Aaron Frost' },
      { id: 2, name: 'Alex Castillo' },
      { id: 3, name: 'Alex Eagle' },
      { id: 4, name: 'Alex Rickabaugh' },
      { id: 5, name: 'Andrew Kushnir' },
      { id: 6, name: 'Andrew Seguin' },
      { id: 7, name: 'Asaad Saad' },
      { id: 8, name: 'Asim Hussain' },
      { id: 9, name: 'Aspen Payton' },
      { id: 10, name: 'Ben Lesh' },
      { id: 11, name: 'Bill Odom' },
      { id: 12, name: 'Brad Green' },
      { id: 13, name: 'Brad Mcalister' },
      { id: 14, name: 'Ryan Chenkie' },
      { id: 15, name: 'Brandon Roberts' },
      { id: 16, name: 'Bret Mcgowen' },
      { id: 17, name: 'Brian Love' },
      { id: 18, name: 'Chloe Condon' },
      { id: 19, name: 'Chris Noring' },
      { id: 20, name: 'Dan Muller' },
      { id: 21, name: 'Dan Wahlin' },
      { id: 22, name: 'Deborah Kurata' },
      { id: 23, name: 'Dylan Johnson' },
      { id: 24, name: 'Elad Bezalel' },
      { id: 25, name: 'Ely Lucas' },
      { id: 26, name: 'Eric Simons' },
      { id: 27, name: 'George Kalpakas' },
      { id: 28, name: 'Igor Minar' },
      { id: 29, name: 'James Daniels' },
      { id: 30, name: 'Jason Aden' },
      { id: 31, name: 'Jason Dobry' },
      { id: 32, name: 'Jeff Cross' },
      { id: 33, name: 'Jennifer Wadella' },
      { id: 34, name: 'Jeremy Elbourn' },
      { id: 35, name: 'Jesse Sanders' },
      { id: 36, name: 'Jo hanna Pearce' },
      { id: 37, name: 'Joe Eames' },
      { id: 38, name: 'Joey Perrott' },
      { id: 39, name: 'John Niedzwiecki' },
      { id: 40, name: 'John Papa' },
      { id: 41, name: 'Kaitlyn Ekdahl' },
      { id: 42, name: 'Kamil Mysliwiec' },
      { id: 43, name: 'Kara Erickson' },
      { id: 44, name: 'Katerina Skroumpelou' },
      { id: 45, name: 'Keen Yee Liau' },
      { id: 46, name: 'Kern Zhao' },
      { id: 47, name: 'Kevin Schuchard' },
      { id: 48, name: 'Kim Maida' },
      { id: 49, name: 'Luis Aviles' },
      { id: 50, name: 'Manfred Steyer' },
      { id: 51, name: 'Matias Niemelä' },
      { id: 52, name: 'Maxim Koretskyi' },
      { id: 53, name: 'Maxim Salnikov' },
      { id: 54, name: 'Melina Mejía Bedoya' },
      { id: 55, name: 'Michael Hladky' },
      { id: 56, name: 'Mike Brocchi' },
      { id: 57, name: 'Mike Hartington' },
      { id: 58, name: 'Mike Pearson' },
      { id: 59, name: 'Mike Ryan' },
      { id: 60, name: 'Miles Malerba' },
      { id: 61, name: 'Minko Gechev' },
      { id: 62, name: 'Nicole Oliver' },
      { id: 63, name: 'Rachel Noccioli' },
      { id: 64, name: 'Rado Kirov' },
      { id: 65, name: 'Reid Villeneuve' },
      { id: 66, name: 'Rob Wormald' },
      { id: 67, name: 'Sam Julien' },
      { id: 68, name: 'Sander Elias' },
      { id: 69, name: 'Sani Yusuf' },
      { id: 70, name: 'Stephen Fluin' },
      { id: 71, name: 'Stephen Petranek' },
      { id: 72, name: 'Thomas Burleson' },
      { id: 73, name: 'Tracy Lee' },
      { id: 73, name: 'Vikram Subramanian' }
    ];

    return { names };
  }
}
